on: [push]

name: check-no-error

jobs:
  check-no-error:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.0'
      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Query dependencies
        run: Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds')"
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-4.0.0-${{ hashFiles('depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-4.0.0-        
      - name: Install renv
        run: Rscript -e "install.packages('renv')"
      - name: Restore packages
        run: Rscript -e "renv::restore()"
#      - name: Test
#        run: Rscript ~/work/test_r_gh_actions/test_r_gh_actions/testthat/test-test_r_gh_actions.R
      - name: List files
        run: ls -R
